import Head from 'next/head'
import Image from 'next/image'
import Confirm from '../components/Confirm'
import LocationSelector from '../components/LocationSelector'
import Map from '../components/Map'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=' overflow-scroll scrollbar-hide' >
      <Head>
        <title>Uber</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* main */}


      <div className='h-screen w-screen fex flex-col'>

        <Navbar />

        <div className=" h-full w-screen flex-1 z-10">

          <Map />

        </div>


        <div className='h-full w-[400px] ml-[1rem] py-[3rem] absolute top-0 p-4 left-0 flex flex-col justify-end z-20'>
          <div className='h-full max-h-[700px] bg-white  rounded-xl hover:scale-105 hover:shadow-2xl hover:shadow-slate-300  flex flex-col overflow-scroll scrollbar-hide' >


            <LocationSelector />

            <Confirm />


          </div>

        </div>

      </div>



      {/* end */}


    </div>
  )
}
